[package]
name = "ijazandcompany"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "ijazandcompany_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.53.1", features = ["full"] }
sqlx = { version = "0.9.0", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "macros",
    "sqlite",
] }
dotenv = "0.15.0"
tauri-plugin-sql = { version = "2.4.0", features = ["sqlite", "postgres"] }
bcrypt = "0.19.2"
uuid = { version = "1.24.0", features = ["v4"] }
calamine = { version = "0.36.1", features = ["chrono"] }
csv = "1.4.0"
zip = { version = "8.6.0", features = ["deflate"] }
quick-xml = { version = "0.41.0", features = ["serialize"] }
chrono = "0.4.45"
dirs = "6.0.0"
