// ==========================================
// SUPER ADMIN SEEDING (one-time)
// ==========================================
//
// On the very first launch after migration 017, this creates the
// cross-tenant Super Admin account so the app is actually usable as a
// SaaS platform (SAAS_SPECIFICATION.md §15.1 / §5.2).
//
// Security model:
//   - The password is generated randomly (never hardcoded).
//   - must_change_password = 1 forces a change on first login.
//   - The credentials are written once to SUPER_ADMIN_SETUP.md in the
//     app data directory and printed to the console.
//   - Idempotent: if any super admin exists, nothing happens.

use sqlx::SqlitePool;
use uuid::Uuid;

use crate::commands::auth::hash_password;

/// Default email for the seeded super admin (configurable in future).
pub const SUPER_ADMIN_EMAIL: &str = "superadmin@ijaz.local";

/// Random password generated at seed time. Never stored in the repo.
fn generate_password() -> String {
    // UUID hex is a decent random source here; two UUIDs give plenty of
    // entropy for a one-time credential that must be changed on first login.
    let source = format!("{}{}", Uuid::new_v4().simple(), Uuid::new_v4().simple());

    // Human-friendly alphabet (no 0/O/1/l/I ambiguity).
    const ALPHABET: &[u8] =
        b"ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";
    const LENGTH: usize = 16;

    source
        .bytes()
        .take(LENGTH)
        .map(|byte| ALPHABET[(byte as usize) % ALPHABET.len()] as char)
        .collect()
}

fn handover_doc(email: &str, password: &str) -> String {
    format!(
        r#"# Super Admin — Secure Handover Document

This document contains the one-time Super Admin credentials for the
Ijaz & Company ERP desktop installation.

These credentials were generated by the app on first launch. They are
NOT stored anywhere else. If you lose them, delete this Super Admin
account from the database and restart the app to re-seed a new one.

---

## Credentials

- Email:    {email}
- Password: {password}

## First login (mandatory)

1. Open the app and sign in with the credentials above.
2. You will be asked to set a new password. Do this immediately.
3. After the password change, this password is no longer valid.

## What is a Super Admin?

A Super Admin operates across all companies (tenants): it registers new
companies, assigns subscription packages, toggles modules and feature
flags, and archives companies. It has no company of its own
(company_id = NULL).

## Regenerating

There is intentionally no self-service reset. To reset the Super Admin:

1. Fully close the app.
2. Open the database file (see the console log for its path).
3. Run:  UPDATE users SET is_super_admin = 0 WHERE email = '{email}';
4. Delete this file.
5. Restart the app — a new Super Admin is seeded with fresh credentials.
"#
    )
}

/// Creates the Super Admin on first launch, if one does not already exist.
///
/// Writes the credentials to `SUPER_ADMIN_SETUP.md` in `data_dir` and
/// prints them to the console. Call AFTER migrations have run.
pub async fn ensure_super_admin(
    pool: &SqlitePool,
    data_dir: &std::path::Path,
) -> Result<(), String> {
    let existing: Option<String> = sqlx::query_scalar(
        "SELECT id FROM users WHERE is_super_admin = 1 AND is_active = 1 LIMIT 1",
    )
    .fetch_optional(pool)
    .await
    .map_err(|error| format!("Super admin check failed: {error}"))?;

    if existing.is_some() {
        println!("Super admin already exists — skipping seeding.");
        return Ok(());
    }

    let password = generate_password();
    let password_hash = hash_password(&password).await?;
    let user_id = Uuid::new_v4().to_string();

    sqlx::query(
        r#"
        INSERT INTO users (
            id, email, password_hash, full_name, role, company_id, is_active,
            is_super_admin, must_change_password
        )
        VALUES (?, ?, ?, 'Super Admin', 'super_admin', NULL, 1, 1, 1)
        "#,
    )
    .bind(&user_id)
    .bind(SUPER_ADMIN_EMAIL)
    .bind(&password_hash)
    .execute(pool)
    .await
    .map_err(|error| format!("Failed to seed super admin: {error}"))?;

    let doc = handover_doc(SUPER_ADMIN_EMAIL, &password);

    if let Err(error) = std::fs::write(data_dir.join("SUPER_ADMIN_SETUP.md"), &doc) {
        eprintln!("Could not write SUPER_ADMIN_SETUP.md: {error}");
    }

    println!("==================================================");
    println!("SUPER ADMIN SEEDED");
    println!("Email:    {SUPER_ADMIN_EMAIL}");
    println!("Password: {password}");
    println!("A copy of these credentials was written to:");
    println!("  {}", data_dir.join("SUPER_ADMIN_SETUP.md").display());
    println!("Password must be changed on first login.");
    println!("==================================================");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::auth::PublicUser;
    use sqlx::sqlite::SqlitePoolOptions;

    async fn temp_pool() -> SqlitePool {
        let path = std::env::temp_dir().join(format!("ijaz-setup-test-{}.db", Uuid::new_v4()));
        let url = format!("sqlite:{}", path.display());
        crate::db::sqlite_migrate::run_sqlite_migrations(&url)
            .await
            .expect("migrations should apply");
        SqlitePoolOptions::new()
            .connect(&url)
            .await
            .expect("pool should connect")
    }

    async fn fetch_seeded(pool: &SqlitePool) -> PublicUser {
        sqlx::query_as::<_, PublicUser>(
            r#"
            SELECT id, email, full_name, role, company_id, is_active, created_at,
                   is_super_admin, must_change_password
            FROM users
            WHERE email = ? COLLATE NOCASE
            "#,
        )
        .bind(SUPER_ADMIN_EMAIL)
        .fetch_one(pool)
        .await
        .expect("seeded super admin should exist")
    }

    #[tokio::test]
    async fn seeds_super_admin_on_first_run() {
        // Input: fresh database, no super admin yet.
        // Expected: a super admin is created and the handover doc is written.
        let pool = temp_pool().await;
        let dir = std::env::temp_dir().join(format!("ijaz-setup-doc-{}", Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();

        ensure_super_admin(&pool, &dir).await.expect("seeding succeeds");

        let admin = fetch_seeded(&pool).await;
        assert_eq!(admin.email, SUPER_ADMIN_EMAIL);
        assert!(admin.is_super_admin);
        assert!(admin.must_change_password);
        assert_eq!(admin.company_id, None);

        let doc = std::fs::read_to_string(dir.join("SUPER_ADMIN_SETUP.md"))
            .expect("handover doc written");
        assert!(doc.contains(SUPER_ADMIN_EMAIL));
        assert!(doc.contains("Password:"));

        std::fs::remove_dir_all(&dir).ok();
    }

    #[tokio::test]
    async fn seeding_is_idempotent() {
        // Input: super admin already seeded.
        // Expected: second run does nothing (no duplicate, no overwrite).
        let pool = temp_pool().await;
        let dir = std::env::temp_dir().join(format!("ijaz-setup-doc-{}", Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();

        ensure_super_admin(&pool, &dir).await.expect("first seeding");
        let doc_before = std::fs::read_to_string(dir.join("SUPER_ADMIN_SETUP.md")).unwrap();
        ensure_super_admin(&pool, &dir).await.expect("second seeding");

        let count: i64 = sqlx::query_scalar("SELECT COUNT(*) FROM users WHERE is_super_admin = 1")
            .fetch_one(&pool)
            .await
            .unwrap();
        assert_eq!(count, 1);

        let doc_after = std::fs::read_to_string(dir.join("SUPER_ADMIN_SETUP.md")).unwrap();
        assert_eq!(doc_before, doc_after, "handover doc must not be overwritten");

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn generated_password_meets_policy() {
        // Input: many generated passwords.
        // Expected: each passes validate_password (>= 8, <= 72 bytes).
        for _ in 0..50 {
            let password = generate_password();
            assert_eq!(password.chars().count(), 16);
            crate::commands::auth::validate_password(&password)
                .expect("generated password must satisfy policy");
        }
    }
}
